-- Fix admin password
-- Generate new BCrypt hash for password: 230305
USE ev_service_center;

-- First, let's see current admin user
SELECT user_id, email, full_name, role, 
       SUBSTRING(password, 1, 20) as password_preview 
FROM users 
WHERE email = 'admin@evsc.com';

-- Update with a freshly generated BCrypt hash for "230305"
-- This is a known working hash generated by BCrypt with strength 10
UPDATE users 
SET password = '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhCa'
WHERE email = 'admin@evsc.com';

-- Verify update
SELECT user_id, email, full_name, role, 
       SUBSTRING(password, 1, 60) as password_full 
FROM users 
WHERE email = 'admin@evsc.com';

